Iterable/react-native-sdk

- android/build.gradle
Adding dependency using `api` keyword instead of `implementation` allows chained access to library. This allows app to use methods from internal library. More description given in the JIRA ticket with stack overflow link
> [MOB-1893] - Access IterableSDK methods from RN Android

- android/build.gradle
This update will solve problems where trackInAppClick were not getting registered.
Also, going forward, we can update the Android Version in RNSDK as a part of release process if everything looks okay.
> [MOB-1922] - Update RN Android to 3.2.5

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
Using rejecters where promises are available. In future, even in void functions, we should use rejecters to indicate failures in request fetched from RN side and promise resolve success if void methods are called successfully.
> [MOB-1969] - RN Android - Using rejecters where applicable

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
Fixes #76.
I went tracing through this and [iterable/iterable-android-sdk](https://github.com/Iterable/iterable-android-sdk) to figure out why we had some many issues with our Android app not bring brought into focus. I'll lay out what I found here, starting at the top level.
1. The actual `config.customActionHandler` you assign is fired [here](https://github.com/Iterable/react-native-sdk/blob/baea2e90c162d6bac72ab6a9f188f82cef5b5e8a/ts/Iterable.ts#L199), via `RNEventEmitter`. Note that nothing is actually done with the return value from your JS handler.
2. The event which executes the above is triggered in native Android [here](https://github.com/Iterable/react-native-sdk/blob/459201fa5da4d3022c69a9e7ad528d38ea63e581/android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java# …
> Bug Fix: Android app not focused when using urlHandler or customActionHandler

- android/src/main/java/com/iterable/reactnative/Serialization.java
* none
* just get rid of some Android Studio warnings
> fix some android studio warnings/recommendations

- android/build.gradle
https://iterable.atlassian.net/browse/MOB-2591
This will update the Android dependency to 3.2.10 which takes care of `firebase_database_url` error faced by some customers
> [MOB-2591] - Update Android dependency to 3.2.10

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
Add `setReadForMessage` to Android bridge
> Add setReadForMessage to Android bridge

- ios/RNIterableAPI/ReactIterableAPI.swift
* [MOB-2731](https://iterable.atlassian.net/browse/MOB-2731)
* add a catch for when the auth retrieval times out in the RN + iOS bridge
> [MOB-2731] add case for auth token retrieval timing out

- ts/IterableInAppClasses.ts
* [MOB-3129](https://iterable.atlassian.net/browse/MOB-3129)
* fixes the `subtitle` naming in `IterableInboxMetadata`
> [MOB-3129] fix naming of subtitle in inbox metadata

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- ios/RNIterableAPI/ReactIterableAPI.swift
These changes fix a crash on Android when calling this method from non-UI thread contexts (ie setTimeout in JS); iOS needed similar edits to fix functionality although a crash wasn't occurring there
> Fixes for setting autoDisplayPaused flag in correct threads

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
Fixes #167
This makes it match the iOS signature and fulfills what typescript says will be there.
This does not actually handle any errors so that should probably be added at some point in the future. This is mostly just to unblock ourselves as we are implementing the SDK. If someone wants to point me into the right direction for errors that I should be checking for then I am happy to do so. I see this as a small step in the right direction to prevent valid typescript applications from crashing unexpectedly.
> Added a dummy promise that returns true for android API initialization

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
* [MOB-3362](https://iterable.atlassian.net/browse/MOB-3362)
* creates and wraps the `dataFields` serialization to allow `null`
* slight formatting consistency changes
* fixes https://github.com/Iterable/react-native-sdk/issues/198
> [MOB-3362] create and use wrapped dataFields serialization

- android/src/main/java/com/iterable/iterableapi/RNIterableInternal.java
- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- ts/Iterable.ts
* [MOB-3672](https://iterable.atlassian.net/browse/MOB-3672)
* allows `trackInAppClose` to take a `null` `clickedUrl` parameter when there's no associated URL with the event (e.g. back button or `dismiss`)
* slight refactoring to use standardized API calls
> [MOB-3672] allow track in app close to take null clickedUrl

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
This PR stops the following warnings that are are being triggered on React Native 0.65 on Android:
- ``WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.``
- ``WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.``
The warnings are due to this commit in the react-native repo: https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2
Here are a few examples of the same fix being applied in other repos as well:
- https://github.com/software-mansion/react-native-reanimated/pull/2316/files
- https://github.com/notifee/react-native-notifee/pull/368/files
- https://github.com/invertase/react-native-firebase/pull/5616/files
> react-native 0.65 android event emitter stubs

- ts/IterableInboxMessageDisplay.tsx
* [MOB-3734](https://iterable.atlassian.net/browse/MOB-3734)
This pull request addresses some errors I discovered when testing the inbox events. The close events were being counted twice when dismiss button was clicked. Also, a close event was not being registered for the deep link buttons. Now, close events are registered for both the invalid link and the deep link. I matched this functionality with the iOS inbox.
> [MOB-3734] address inbox event errors

- ts/IterableInboxMessageCell.tsx
- ts/IterableInboxMessageDisplay.tsx
* [MOB-3735] (https://iterable.atlassian.net/browse/MOB-3735)
A warning occurs when the delete link or button within the in-app message is clicked on the last message in the message list. 
This pull request adds a flag that is toggled to true when the IterableInboxMessageDisplay component is mounted. A useEffect cleanup function is added to toggle the flag to false when the component is unmounted.
see the following reference => [Here](https://www.debuggr.io/react-update-unmounted-component/)
[MOB-3735]: https://iterable.atlassian.net/browse/MOB-3735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3735] addresses delete link warning

- ts/IterableInboxMessageDisplay.tsx
* [MOB-3910] (https://iterable.atlassian.net/browse/MOB-3910)
This pull request includes adding the clicked url to the trackInAppClose function call.
[MOB-3910]: https://iterable.atlassian.net/browse/MOB-3910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3910] null clicked url for triggered events

- ts/IterableInboxMessageCell.tsx
* [MOB-3864] (https://iterable.atlassian.net/browse/MOB-3864)
This pull request includes a small change that allows the delete slider to match the message row height when the styling customized. If the default inbox component is used, the delete slider has a default height. Also, I passed the message row height from the custom layout as a return value that is used by the IterableInboxMessageCell component.
[MOB-3864]: https://iterable.atlassian.net/browse/MOB-3864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3864] update slider height with customization and custom layout

- ts/IterableInbox.tsx
- ts/IterableInboxCustomizations.ts
- ts/IterableInboxMessageDisplay.tsx
* [MOB-4037] (https://iterable.atlassian.net/browse/MOB-4037)
This pull request updates the return to inbox functionality, so that for all actions involving returning to the inbox the animation completes first. For example, when a user selects the delete button, the message display closes first before the message is deleted.
[MOB-4037]: https://iterable.atlassian.net/browse/MOB-4037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4037] adds delay to deleteRow call to allow message display to be dismissed

- ts/IterableInboxMessageCell.tsx
* [MOB-4321] (https://iterable.atlassian.net/browse/MOB-4321)
This pull request increases the default delete slider height to 150 to account for increasing the number of lines in the message cell body to 3.
[MOB-4321]: https://iterable.atlassian.net/browse/MOB-4321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4321] increases default delete slider height

- ts/IterableInboxMessageCell.tsx
* [MOB-4342] (https://iterable.atlassian.net/browse/MOB-4342)
This pull request implements the swiping threshold for the pan responder that serves as the delete slider. The swiping flag is also set to false after the pan responder is released.
[MOB-4342]: https://iterable.atlassian.net/browse/MOB-4342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4342] implement swiping threshold

- ts/IterableInbox.tsx
* [MOB-4336] (https://iterable.atlassian.net/browse/MOB-4336)
This pull request sets the returnToInboxTrigger as an optional parameter to the inbox component.
[MOB-4336]: https://iterable.atlassian.net/browse/MOB-4336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4336] sets the returnToInboxTrigger as an optional parameter

- ts/IterableInbox.tsx
- ts/IterableInboxMessageDisplay.tsx
* [MOB-4337] (https://iterable.atlassian.net/browse/MOB-4337)
This pull request reorganizes the rendering of the inbox component as a button vs. as a navigation tab. When the inbox is set up as a button, the inbox is rendered within a view rather than a safe area view.
[MOB-4337]: https://iterable.atlassian.net/browse/MOB-4337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4337] reorganizes the rendering of the inbox for button vs. tab

- ts/IterableInbox.tsx
* [MOB-4344] (https://iterable.atlassian.net/browse/MOB-4344)
This pull request adds the end session function call when the inbox component unmounts. This is used for cases like toggling the inbox with a toggle button.
[MOB-4344]: https://iterable.atlassian.net/browse/MOB-4344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4344] end session on unmount

- ts/__tests__/Iterable.spec.ts
- ts/index.ts
No tickets - PR is to address this issue https://github.com/Iterable/react-native-sdk/issues/356
After the 1.3.1 release, `Iterable` and `IterableConfig` were no longer exported from index.ts. This PR adds them back in. I've also made the unit tests import from index.ts rather than the implementation files, as consumers will be importing from index (so if this happens again, it will be caught by unit tests in CI).
---
If these removals were intentional and there's a new way to import these classes from the SDK, feel free to close out this PR. Documentation would need to be updated in that case as found here: https://support.iterable.com/hc/en-us/articles/360045714132-Installing-Iterable-s-React-Native-SDK-#_5-import-classes-as-needed
> ready: Add missing Iterable and IterableConfig exports back to index.ts

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
* [MOB-4692](https://iterable.atlassian.net/browse/MOB-4692)
Android SDK has added functionality to trigger onSuccess and onFailure callbacks.
Because RN SDK’s internal Java methods implement AuthHandler, it needs to implement the additional methods as well.
This will prevent any build errors also prepare for RN’s version of authHandler success and failure callbacks to be implemented next.
> [MOB-4692] - Override authHandler's new methods

- ts/Iterable.ts
- ts/IterableAction.ts
- ts/__tests__/Iterable.spec.ts
* [MOB-4703](https://iterable.atlassian.net/browse/MOB-4703)
We're serializing the context with `source` as the field name, but were using `actionSource` when deserializing, so the field was always `undefined`.
> [MOB-4703] Fix action source deserialization

- README.md
* [MOB-4808](https://iterable.atlassian.net/browse/MOB-4808)
This pull request adds a version mapping table to the readme file. This will allow users of the RN SDK to have a quick reference of what versions of our native SDKs each version of the React Native SDK points to. Also, included are the appropriate links to the npm package and the associated release tags for the native SDKs.
> [MOB-4808] add version mapping to readme

- android/src/main/java/com/iterable/reactnative/Serialization.java
- ts/IterableConfig.ts
* [MOB-4917](https://iterable.atlassian.net/browse/MOB-4917)
* allows RN SDK devs to configure the android SDK `useInMemoryStorageForInApps` config option
> [MOB-4917] add downstream support for the android SDK in memory option 

- ts/__tests__/Iterable.spec.ts
* [MOB-5253](https://iterable.atlassian.net/browse/MOB-5253)
This pull request updates the config object default values in unit tests.
> [MOB-5253] update config object default values in unit tests

- ts/__mocks__/MockRNIterableAPI.ts
* [MOB-5198](https://iterable.atlassian.net/browse/MOB-5198)
This pull request updates the return types for the getEmail and getUSerId methods for the mock RNIterableAPI.
> [MOB-5198] updates return types for getEmail and getUserId methods of MockRNIterableAPI

- ts/__mocks__/MockRNIterableAPI.ts
- ts/__tests__/IterableInApp.spec.ts
🔹 JIRA Ticket(s) if any
* [MOB-5245](https://iterable.atlassian.net/browse/MOB-5245)
This pull request creates a setMessages function for the MockRNIterableAPI class for testing purposes and refactors the getMessages unit test to remove setting messages from the test body.
> [MOB-5248] refactors getMessages unit test

- android/build.gradle
* [MOB-5316](https://iterable.atlassian.net/browse/MOB-5316)
This pull request adds the safeExtGet method to inherit the gradle build config values from the parent project rather than hardcoding them.
> [MOB-5316] adds safeExtGet method to build.gradle

- android/src/main/java/com/iterable/reactnative/Serialization.java
- ios/RNIterableAPI/Serialization.swift
`expiringAuthTokenRefreshPeriod` was not being passed to the `IterableConfig` in swift or java, leaving it to the default 60s.
> Pass expiringAuthTokenRefreshPeriod to native sdks

- ts/Iterable.ts
* [MOB-6063](https://iterable.atlassian.net/browse/MOB-6063)
This pull request updates the parameter types for setEmail and setUserId. This stems from reported issues with setEmail as discussed [here](https://iterable.atlassian.net/browse/MOB-6063). In our documentation, we ask customers to pass in a value of null to log out.
[MOB-6063]: https://iterable.atlassian.net/browse/MOB-6063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6063] updates parameter types for setEmail and setUserId

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
* [MOB-6471](https://iterable.atlassian.net/browse/MOB-6471)
> Android counterpart now respects the `mergeNestedObjects` flag passed in the parameters
[MOB-6471]: https://iterable.atlassian.net/browse/MOB-6471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB - 6471] Fix - Merge Nested Object when update

- SampleApp/javascript/js/App.js
- SampleApp/javascript/js/BannerViewScreen.d.ts
- SampleApp/javascript/js/BannerViewScreen.js
- SampleApp/javascript/js/HomeScreen.js
- SampleApp/javascript/js/components/IterableBannerView.tsx
- SampleApp/javascript/js/types/commonType.ts
- SampleApp/typescript/ios/SampleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ts/components/IterableBannerView.tsx
- ts/index.ts
- ts/types/commonType.ts
> Added Banner View

- SampleApp/javascript/js/SettingsTab.js
- SampleApp/typescript/ios/SampleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- SampleApp/typescript/ts/SettingsTab.tsx
- **Release Notes**
> We have successfully implemented support for the userId in Sample App for both JavaScript and TypeScript Apps.
- **Test Steps**
> 1. Run the Sample App.
> 2. Navigate to the Settings tab.
> 3. Locate the field for entering email/userId.
> 4. Enter the appropriate value and press the login button.
> 5. Verify that the email/userId is displayed as the user.
> 6. Click the Logout button.
> 7. Confirm that the field for entering email/userId is visible again.
> add support for userId in sample app

- example/src/components/App/App.constants.ts
- example/src/components/App/Main.tsx
- example/src/components/Inbox/Inbox.constants.ts
- example/src/components/Inbox/Inbox.tsx
- example/src/components/Inbox/index.ts
- example/src/constants/routes.ts
- example/src/hooks/useIterableApp.tsx
- example/src/types/navigation.ts
- src/IterableInbox.tsx
- src/IterableInboxMessageDisplay.tsx
- src/IterableInboxMessageList.tsx
- src/index.tsx
* [MOB-10033](https://iterable.atlassian.net/browse/MOB-10033)
Added an inbox to the example app
- cd into the root directory
- run `yarn install`
- cd into the example directory
- follow the instructions for setup in the example directories readme
[MOB-10033]: https://iterable.atlassian.net/browse/MOB-10033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10033] Example App: inbox

- .npmignore
* [MOB-10208](https://iterable.atlassian.net/browse/MOB-10208)
Updated .npmignore to remove lock files and include other unnecessary files.
[MOB-10208]: https://iterable.atlassian.net/browse/MOB-10208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10208] Update .npmignore to include additional default ignores and test files

- example/README.md
- example/src/components/App/App.tsx
- example/src/components/App/Main.tsx
* [MOB-10608](https://iterable.atlassian.net/browse/MOB-10608)
- Removed indicator in message tab in example app
- Added another common error to readme
[MOB-10608]: https://iterable.atlassian.net/browse/MOB-10608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10608] indicator-is-showing-one-unread-message-when-inbox

- CHANGELOG.md
- README.md
- package.json
- src/itblBuildInfo.ts
* [MOB-10588](https://iterable.atlassian.net/browse/MOB-10588)
[MOB-10588]: https://iterable.atlassian.net/browse/MOB-10588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10588] release-2-0-0-beta

- README.md
* [MOB-11189](https://iterable.atlassian.net/browse/MOB-11189)
Add disclaimer about not supporting react new architecture
[MOB-11189]: https://iterable.atlassian.net/browse/MOB-11189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-11189] add-disclaimer-about-not-supporting-new-architectu

- CHANGELOG.md
- README.md
- package.json
- src/itblBuildInfo.ts
* [MOB-11193](https://iterable.atlassian.net/browse/MOB-11193)
Publish 2.0.0-beta.1
[MOB-11193]: https://iterable.atlassian.net/browse/MOB-11193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-11193] publish-2-0-0-beta-1

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- src/embedded/classes/IterableEmbeddedManager.ts
- src/embedded/classes/IterableEmbeddedPlacement.ts
- src/embedded/classes/index.ts
- src/embedded/index.ts
- src/index.tsx
* [MOB-8751](https://iterable.atlassian.net/browse/MOB-8751)
> This pull request 
- creates the `IterableEmbeddedManager`
- creates `getPlacements` on `IterableEmbeddedManager`
- creates `getEmbeddedPlacements` on `RNIterableAPIModule` and `ReactIterableAPI`
Testing:
- native functions have hard coded dummy placements
- the dev app has "get embedded messages" added to the api list under the embedded-testing branch
- you can test passing through embedded placments by changing the hardcoded payload and verifying that it shows up on the app side
- unit tests will be added once the embedded placement class is created on the next PR.
[MOB-8751]: https://iterable.atlassian.net/browse/MOB-8751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8751] create embedded manager

- src/embedded/classes/IterableEmbeddedMessageElementsButton.ts
- src/embedded/classes/IterableEmbeddedMessageElementsButtonAction.ts
> [MOB-XXXX] adds labels for dict

- src/__tests__/IterableEmbeddedMessageDefaultAction.test.ts
- src/__tests__/IterableEmbeddedMessageElements.test.ts
- src/__tests__/IterableEmbeddedMessageText.test.ts
- src/embedded/classes/IterableEmbeddedMessageDefaultAction.ts
- src/embedded/classes/IterableEmbeddedMessageElements.ts
- src/embedded/classes/IterableEmbeddedMessageElementsButtonAction.ts
- src/embedded/classes/IterableEmbeddedMessageText.ts
- src/embedded/classes/index.ts
* [MOB-11551](https://iterable.atlassian.net/browse/MOB-11551)
> This pull request creates the `IterableEmbeddedMessageElements` class.
[MOB-11551]: https://iterable.atlassian.net/browse/MOB-11551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-11551] creates IterableEmbeddedMessageElements class

- src/__tests__/IterableEmbeddedMessage.test.ts
- src/embedded/classes/IterableEmbeddedMessage.ts
* [MOB-7936](https://iterable.atlassian.net/browse/MOB-7936)
> This pull request creates the `IterableEmbeddedMessage` class.
[MOB-7936]: https://iterable.atlassian.net/browse/MOB-7936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7936] creates IterableEmbeddedMessage class

- example/src/components/Login/Login.tsx
- example/src/hooks/useIterableApp.tsx
- package.json
- src/api/NativeRNIterableAPI.ts
- src/api/index.ts
- src/core/classes/Iterable.ts
- src/core/classes/IterableAuthResponse.ts
- src/inApp/classes/IterableInAppManager.ts
- src/inbox/classes/IterableInboxDataModel.ts
- src/inbox/components/IterableInbox.tsx
* [MOB-11826](https://iterable.atlassian.net/browse/MOB-11826)
Created the frontend code necessary to run the iOS code with RN new arch.
This was done to separately reduce an enormous PR, so new arch will temporarily not work.
Building the iOS version of this app in *legacy arch* should work
- open *example>ios>podfile*
- change `ENV['RCT_NEW_ARCH_ENABLED'] = '1'` to `ENV['RCT_NEW_ARCH_ENABLED'] = '0'`
- in *example>ios*, run the following:
- `bundle exec pod deintegrate`
- `rm -rf ~/Library/Developer/Xcode/DerivedData Pods Podfile.lock build ../Gemfile.lock`
- `bundle install`
- `bundle exec pod install`
- in *example* run:
-  `watchman watch-del-all`
- `yarn start --reset-cache`
- build the ios app
The app should build and load correctly
[MOB-11826]: …
> [MOB-11826] make-frontend-api-and-codegen

- ios/RNIterableAPI/RNIterableAPI.h
- ios/RNIterableAPI/RNIterableAPI.mm
* [MOB-11828](https://iterable.atlassian.net/browse/MOB-11828)
Update our codebase to support legacy ios architecture in iOS.
Building the iOS version of this app in *legacy arch* should work
- open *example>ios>podfile*
- change `ENV['RCT_NEW_ARCH_ENABLED'] = '1'` to `ENV['RCT_NEW_ARCH_ENABLED'] = '0'`
- in *example>ios*, run the following:
- `bundle exec pod deintegrate`
- `rm -rf ~/Library/Developer/Xcode/DerivedData Pods Podfile.lock build ../Gemfile.lock`
- `bundle install`
- `bundle exec pod install`
- in *example* run:
-  `watchman watch-del-all`
- `yarn start --reset-cache`
- build the ios app
The app should build and load correctly
[MOB-11828]: https://iterable.atlassian.net/browse/MOB-11828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> [MOB-11828] add-backwards-compatibility

- .github/workflows/unit-test.yml
This PR:
1.  Updates the CI workflow to publish coverage reports to Qlty Cloud (the new version of Code Climate Quality). 
2. Removes references to the (deprecated) `codeclimate-action`
3. @lposen you'll need to store this repo's new [coverage token](https://docs.qlty.sh/migration/coverage#step-2-store-the-coverage-token-as-a-ci-secret-if-not-using-oidc) as a secret (`QLTY_COVERAGE_TOKEN`). You can grab the token from the Project Settings [here](https://qlty.sh/gh/Iterable/projects/react-native-sdk/settings/coverage).
> update coverage reporting for Qlty Cloud

- Iterable-React-Native-SDK.podspec
- example/ios/ReactNativeSdkExample.xcodeproj/project.pbxproj
* [MOB-12123](https://iterable.atlassian.net/browse/MOB-12123)
Change Iterable-iOS-SDK version to 6.5.4.1
[MOB-12123]: https://iterable.atlassian.net/browse/MOB-12123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-12123] add-6-5-4-1-to-react-native-sdk

- .github/workflows/codeql.yml
- example/ios/Podfile
- example/ios/ReactNativeSdkExample.xcodeproj/project.pbxproj
* [PSEC-643](https://iterable.atlassian.net/browse/PSEC-643)
> Enables CodeQL workflow and GitHub Advanced Security on this repo
[PSEC-643]: https://iterable.atlassian.net/browse/PSEC-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Initial CodeQL commit
