- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
Added support for set userId
Changed signature of initializeWithApiKey to take two parameters instead of one (solely for the purpose of making it run and not show error on javascript side). Initialize still needs work where config is built properly.
> [MOB-1419] - Add support for userID

- android/src/main/java/com/iterable/iterableapi/RNIterableInternal.java
- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
> MOB-1493 Add support to GetEmail API

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- android/src/main/java/com/iterable/reactnative/Serialization.java
Add a method getHtmlInAppContentForMessage for RN to be able to get messageContent
> [MOB-1926] - RNAndroid - getHTMLContent

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- package.json
- ts/Iterable.ts
- yarn.lock
JWT auth support for React Native.
> [MOB-2028] JWT bindings

- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- ts/Iterable.ts
…zation is complete.
* [MOB-2492](https://iterable.atlassian.net/browse/MOB-2492)
> Iterable.initialiize(...) react method now returns a promise. We can now know when initialization is finished.
> [MOB-2492] - Need callback for reporting initialization is done

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- ios/RNIterableAPI/Serialization.swift
- ts/IterableInAppClasses.ts
- ts/__tests__/IterableInApp.spec.ts
* [MOB-2459](https://iterable.atlassian.net/browse/MOB-2459)
* adds in-app prioritization variables to be read
* carries over in-app priority functionality from both beta SDKs
> [MOB-2459] in-app prioritization

- ts/IterableInAppClasses.ts
https://iterable.atlassian.net/browse/MOB-2584
1. Changing `as number` to new Date(0)
2. setting the date using method `setUTCMilliseconds`
> [MOB-2584] - null dates fix for Android

- android/build.gradle
https://iterable.atlassian.net/browse/MOB-2590
Updating the beta link from `com.iterable.*' to 'com.github.*'
> [MOB-2590] - Update Android Gradle to newest beta

- README.md
* [MOB-2607](https://iterable.atlassian.net/browse/MOB-2607)
> [MOB-2607] update xcode requirement in README

- Iterable-React-Native-SDK.podspec
Resolves build issue with Xcode 12. More details [here](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116).
Closes #112
> Fix: Xcode 12 compatibility

- package.json
* [MOB-2612](https://iterable.atlassian.net/browse/MOB-2612)
* changes the peer dependencies to allow any version of `react` and `react-native`
> [MOB-2612] shift peer dependency to catch all and add react

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- ios/RNIterableAPI/ReactIterableAPI.swift
- package.json
- yarn.lock
* [MOB-2796](https://iterable.atlassian.net/browse/MOB-2796)
* creates a new stable release for the RN SDK
> [MOB-2796] version 1.0.26

- integration-testing/ios/example/IterableAPISupport.swift
- integration-testing/package.json
- integration-testing/yarn.lock
* [MOB-2815](https://iterable.atlassian.net/browse/MOB-2815)
* points `integration-testing` to use SDK version `1.1.0-beta2`
> [MOB-2815] update integration testing to use 1.1.0-beta2

- integration-testing/package.json
- integration-testing/yarn.lock
* [MOB-2574](https://iterable.atlassian.net/browse/MOB-2574)
> [MOB-2574] update integration testing on stable

- android/src/main/java/com/iterable/reactnative/Serialization.java
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- ios/RNIterableAPI/Serialization.swift
- ts/Iterable.ts
- ts/__tests__/Iterable.spec.ts
* [MOB-2862](https://iterable.atlassian.net/browse/MOB-2862)
> Remove deferred deeplinking.
> [MOB-2862] - Remove deferred deeplinking.

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- android/src/main/java/com/iterable/reactnative/Serialization.java
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- ios/RNIterableAPI/Serialization.swift
- package.json
- ts/Iterable.ts
- ts/IterableInAppClasses.ts
- ts/__tests__/Iterable.spec.ts
- ts/__tests__/IterableInApp.spec.ts
- yarn.lock
* [MOB-2798](https://iterable.atlassian.net/browse/MOB-2798)
* release SDK version 1.0.27
> [MOB-2798] RN SDK release

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- android/src/main/java/com/iterable/reactnative/Serialization.java
- integration-testing/package.json
- ios/RNIterableAPI/Serialization.swift
- ts/Iterable.ts
- ts/__tests__/Iterable.spec.ts
* [MOB-2923](https://iterable.atlassian.net/browse/MOB-2923)
* adds the `trackPurchase` API to the RN SDK
> [MOB-2923] trackpurchase api

- integration-testing/ios/example/IterableAPISupport.swift
- integration-testing/yarn.lock
* [MOB-3027](https://iterable.atlassian.net/browse/MOB-3027)
* fixes errors in integration testing
> [MOB-3027] fix integration testing

- CHANGELOG.md
- Iterable-React-Native-SDK.podspec
- android/build.gradle
- package.json
- yarn.lock
* [MOB-2968](https://iterable.atlassian.net/browse/MOB-2968)
* version 1.1.0 updating
> [MOB-2968] version 1.1.0

- SampleApp/javascript/package.json
- SampleApp/javascript/yarn.lock
- SampleApp/typescript/package.json
- SampleApp/typescript/yarn.lock
- integration-testing/package.json
- integration-testing/yarn.lock
* none
* updating packages and SDK version for related code
> update and upgrade yarn packages

- ts/Iterable.ts
- ts/IterableInAppClasses.ts
- ts/IterableInAppManager.ts
- ts/IterableInAppMessage.ts
- ts/__tests__/IterableInApp.spec.ts
- ts/index.ts
* [MOB-3159](https://iterable.atlassian.net/browse/MOB-3159)
* refactors `IterableInAppMessage` and `IterableInAppManager` out to their own classes
> [MOB-3159] split out in app stuff

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- ts/Iterable.ts
- ts/__mocks__/MockRNIterableAPI.ts
- ts/__tests__/Iterable.spec.ts
* [MOB-3143](https://iterable.atlassian.net/browse/MOB-3143)
* adds the `updateCart` to the RN SDK
> [MOB-3143] updatecart

- inbox/sampleMessageData.js
* N/A
* edits sample in-app data with realistic formatting/fields
> edit inbox sample data

- ts/IterableInboxMessageCell.tsx
- ts/sampleMessageData.js
This pull request makes minor changes to the message cell components and the sample message data so that the variables align properly.
> Minor changes to inbox message cell component and sample message data

- ts/Iterable.ts
- ts/IterableConfig.ts
- ts/index.ts
* N/A
* just had a quick chance to split out `IterableConfig.ts`, no functional change
> separate iterableconfig

- Iterable-React-Native-SDK.podspec
- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- android/build.gradle
- package.json
* [MOB-3264](https://iterable.atlassian.net/browse/MOB-3264)
* this PR should be merged AFTER https://github.com/Iterable/react-native-sdk/pull/170
* updates version numbers of RN SDK and pointers for 1.1.1
> [MOB-3264] update RN SDK pointers and sample app versions

- integration-testing/package.json
* N/A
* bumps version of integration testing
> use SDK version 1.1.1 for integration testing

- package.json
- ts/IterableInbox.tsx
- ts/IterableInboxEmptyState.tsx
- ts/IterableInboxMessageCell.tsx
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageList.tsx
- ts/sampleMessageData.js
- yarn.lock
* [MOB-3141](https://iterable.atlassian.net/browse/MOB-3141)
This pull request includes the message display component and the associated functionality on the inbox component. This pull request uses the updated naming conventions and was tested in the react native dev app. The animations will still need to be implemented which will occur on another pull request
> [MOB-3141] message display component and functionality

- ts/IterableInbox.tsx
* [MOB-3288](https://iterable.atlassian.net/browse/MOB-3288)
This pull request adds the navigation title customization for the IterableInbox component.
> [MOB-3288] navigation title customization

- ts/IterableInbox.tsx
- ts/IterableInboxClickableRow.tsx
- ts/IterableInboxEmptyState.tsx
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageList.tsx
- ts/IterableInboxMessageListItem.tsx
- ts/IterableInboxSwipeableRow.tsx
- ts/messageType.ts
- ts/sampleMessageData.js
- yarn.lock
* [MOB-3287](https://iterable.atlassian.net/browse/MOB-3287)
This pull request provides the capability to customize the empty state title and body. The inbox customizations are passed to the iterableInbox component as a prop. The iterableInbox passes the empty state title and body down to the iterableInboxEmptyState component.
> [MOB-3287] empty state customization

- ts/IterableInbox.tsx
- ts/IterableInboxClickableRow.tsx
- ts/IterableInboxEmptyState.tsx
- ts/IterableInboxMessageList.tsx
- ts/IterableInboxMessageListItem.tsx
- ts/IterableInboxSwipeableRow.tsx
- ts/customizationType.ts
* [MOB-3152](https://iterable.atlassian.net/browse/MOB-3152)
This pull request addresses the customization of the color scheme for the message row. This pull request also edits the rendering of the last message row so that the styling of the message rows are streamlined. The customizeStyles function updates any customization that is sent in as part of the messageRowCustomization object.
> [MOB-3152] message list styling customization

- package.json
- ts/IterableInbox.tsx
- ts/IterableInboxClickableRow.tsx
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageList.tsx
- ts/IterableInboxMessageListItem.tsx
- ts/IterableInboxSwipeableRow.tsx
- ts/messageType.ts
- yarn.lock
* [MOB-3146](https://iterable.atlassian.net/browse/MOB-3146)
This pull request covers the message delete functionality. The message delete animation is encompassed in the IterableInboxSwipeableRow component. The deleteMessage function is passed down to this component. I had to do some modification to the message cell styling in the IterableInboxClickableRow component to match the height of the delete slider.
> [MOB-3146] delete message functionality

- ts/IterableInboxDataModel.ts
* [MOB-3295](https://iterable.atlassian.net/browse/MOB-3295)
* removes listeners
* adds an async version of getting inbox messages
> [MOB-3295] data model fixes

- ts/IterableInboxDataModel.ts
* [MOB-3299](https://iterable.atlassian.net/browse/MOB-3299)
* fixes `setItemForRead`
* adds filter/comparator for messages
* sorts by most recent message by default
> [MOB-3299] data model fixes

- ts/IterableInboxDataModel.ts
* [MOB-3305](https://iterable.atlassian.net/browse/MOB-3305)
* creates a way to get the HTML of an inbox in-app
> [MOB-3305] get inbox in-app HTML

- ts/IterableInbox.tsx
- ts/IterableInboxClickableRow.tsx
- ts/IterableInboxDataModel.ts
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageList.tsx
- ts/IterableInboxMessageListItem.tsx
- ts/IterableInboxSwipeableRow.tsx
* [MOB-3294](https://iterable.atlassian.net/browse/MOB-3294)
This pull request incorporates the data model into the react native inbox and allows for messages to be retrieved from the Iterable platform. The message list is populated with the user's messages and the message display shows the title.
> [MOB-3296] incorporate inbox data model

- ts/IterableInbox.tsx
- ts/IterableInboxMessageDisplay.tsx
* [MOB-3312](https://iterable.atlassian.net/browse/MOB-3312)
This PR renames the branch to the appropriate ticket.
> [MOB-3312] animate message display

- ts/IterableInbox.tsx
- ts/IterableInboxDataModel.ts
* [MOB-3302](https://iterable.atlassian.net/browse/MOB-3302)
* refactor and rewrite inbox data model to avoid syncing bugs and to remove irrelevant code
> [MOB-3302] rewrite inbox data model

- inbox/components/EmptyState/EmptyState.tsx
- inbox/components/MessageList/MessageList.tsx
- package.json
- ts/__tests__/EmptyState.spec.tsx
- ts/__tests__/Inbox.spec.tsx
- ts/__tests__/MessageList.spec.tsx
- yarn.lock
* [MOB-3213](https://iterable.atlassian.net/browse/MOB-3213)
Adds unit testing covering MOB-3213.
> adds remaining unit tests

- ts/IterableInboxClickableRow.tsx
- ts/IterableInboxCustomizations.ts
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageListItem.tsx
- ts/IterableInboxSwipeableRow.tsx
* [MOB-3416](https://iterable.atlassian.net/browse/MOB-3416)
This pull request addresses the styling issues with the message display. The render HTML element is changed to a WebView component that is part of the react native library.
> [MOB-3416] address message display styling issues

- ts/IterableInbox.tsx
- ts/IterableInboxClickableRow.tsx
- ts/IterableInboxCustomizations.ts
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageList.tsx
- ts/IterableInboxMessageListItem.tsx
- ts/IterableInboxSwipeableRow.tsx
- tsconfig.json
* [MOB-3462](https://iterable.atlassian.net/browse/MOB-3462)
This pull request allows for a default inbox to be rendered when there are no customizations or message list item layout sent from the customer's application.
> [MOB-3462] default inbox without customization

- ts/IterableInboxMessageListItem.tsx
* [MOB-3416](https://iterable.atlassian.net/browse/MOB-3416)
This pull request includes minor edits to the inbox branch to get rid of older versions of the code base.
> adds minor edits to the inbox branch

- ts/IterableInboxMessageList.tsx
- ts/IterableInboxSwipeableRow.tsx
* [MOB-3469](https://iterable.atlassian.net/browse/MOB-3469)
This pull request includes the functionality to suppress message list scrolling when the message list item is being swiped to delete.
> [MOB-3469] suppress message list scrolling

- ts/IterableInboxCustomizations.ts
- ts/IterableInboxMessageListItem.tsx
- ts/IterableInboxSwipeableRow.tsx
* [MOB-3461](https://iterable.atlassian.net/browse/MOB-3461)
This pull request addresses the styling issues for the message list item. It sets the message list item to a constant height and sets the message body to set number of lines. It also addresses errors with the view element styling and conditionally renders the message list item on device rotation.
> [MOB-3461] update styling of message body to fit container

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- android/src/main/java/com/iterable/reactnative/Serialization.java
* [MOB-3522](https://iterable.atlassian.net/browse/MOB-3522)
* adds PLACEHOLDER functions for the RN android bridge for inbox session tracking
* android SDK implementation will be completed at a later date in ticket MOB-3386
> [MOB-3522] RN android bridge session tracking placeholders

- ts/IterableInbox.tsx
- ts/useInboxChangedListener.ts
* [MOB-3519](https://iterable.atlassian.net/browse/MOB-3519)
* separates out inbox changed/silent push notification functionality
> [MOB-3519] inbox changed hook

- ts/InboxImpressionRowInfo.ts
- ts/IterableInboxDataModel.ts
* [MOB-3388](https://iterable.atlassian.net/browse/MOB-3388)
* adds data model integrations for inbox session tracking
* creates data type for tracking
> [MOB-3388] add foundation for inbox session tracking to model

- ts/IterableInbox.tsx
- ts/IterableInboxClickableRow.tsx
- ts/IterableInboxDataModel.ts
- ts/IterableInboxMessageList.tsx
- ts/IterableInboxMessageListItem.tsx
- ts/IterableInboxSwipeableRow.tsx
* [MOB-3460](https://iterable.atlassian.net/browse/MOB-3460)
* adds a way to format timestamps of inbox cells inside `IterableInboxDataModel`
* adds and uses a default formatting of timestamps
> [MOB-3460] date formatting

- ts/IterableInbox.tsx
- yarn.lock
This pull request uncomments out and tests the message list. It adds the Platform API to the IterableInbox component. The headline height and the top margin of the message list container will be conditionally rendered based on iOS or Android implementation.
> [MOB-3506] android message list updates

- package.json
- ts/IterableInbox.tsx
- ts/IterableInboxClickableRow.tsx
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageList.tsx
- ts/IterableInboxSwipeableRow.tsx
- yarn.lock
* [MOB-3506](https://iterable.atlassian.net/browse/MOB-3506)
This pull request includes merging all the changes to get the android implementation up to current without the message links and session tracking.
> [MOB-3506] test out mobile inbox on Android

- ts/IterableInboxMessageDisplay.tsx
* [MOB-3620] (https://iterable.atlassian.net/browse/MOB-3620)
This pull request provides in-app link click tracking as part of the handleHTMLmessage function.
[MOB-3620]: https://iterable.atlassian.net/browse/MOB-3620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3620] track in-app click events

- ts/IterableInbox.tsx
* [MOB-3621] (https://iterable.atlassian.net/browse/MOB-3621)
This pull request includes the inbox in-app open event tracking as part of the handleMessageSelect function.
[MOB-3621]: https://iterable.atlassian.net/browse/MOB-3621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3621] track in-app open events

- ts/Iterable.ts
* N/A
* changes `clickedUrl` to be fully optional
> make trackInAppClose clickedUrl param optional

- ts/IterableInboxMessageDisplay.tsx
* [MOB-3622](https://iterable.atlassian.net/browse/MOB-3622)
This pull request includes adding in-app close events to the handleHTMLmessage function when the dismiss link is clicked and to the onPress prop of the return to inbox button.
> [MOB-3622] track in-app close events

- android/build.gradle
* [MOB-3684](https://iterable.atlassian.net/browse/MOB-3684)
* continues the linking of the local android SDK
> [MOB-3684] create proper link to local RN SDK

- ts/IterableInbox.tsx
- ts/IterableInboxMessageDisplay.tsx
* [MOB-3621](https://iterable.atlassian.net/browse/MOB-3621)
* [MOB-3622](https://iterable.atlassian.net/browse/MOB-3622)
This pull request includes the in-app open and close events implementation outside of the HTML links.
> [MOB-3621&3622] inbox in-app open and close events

- ts/IterableInboxMessageDisplay.tsx
* [MOB-3661] (https://iterable.atlassian.net/browse/MOB-3661)
This pull request includes adding the external linking functionality. The external linking needs to be dealt with by the onShouldStartLoadingWithRequest prop since we need to tell the webview to stop loading if the link goes to an external link (starts with http)..
[MOB-3661]: https://iterable.atlassian.net/browse/MOB-3661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3661] adds external linking functionality

- ts/IterableInboxMessageDisplay.tsx
* [MOB-3669] (https://iterable.atlassian.net/browse/MOB-3669)
This pull request includes updating the handleHTMLMessage function. This update allows the inbox to stay on the message display if a link does not have a correct HTML link.
[MOB-3669]: https://iterable.atlassian.net/browse/MOB-3669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3669] handling error links

- ts/IterableInboxMessageDisplay.tsx
* [MOB-3737](https://iterable.atlassian.net/browse/MOB-3737)
This pull request addresses the missing close event for the deep links.
> [MOB-3737] address missing close event

- ts/Iterable.ts
- ts/IterableConfig.ts
- ts/IterableInAppManager.ts
- ts/IterableInAppMessage.ts
- ts/IterableInbox.tsx
- ts/IterableInboxDataModel.ts
- ts/IterableInboxEmptyState.tsx
- ts/IterableInboxMessageCell.tsx
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageList.tsx
- ts/index.ts
- ts/useAppStateListener.ts
- ts/useDeviceOrientation.tsx
* [MOB-3726](https://iterable.atlassian.net/browse/MOB-3726)
This pull request converts all function expressions to function declarations across all components. I also standardized all the imports across all files.
> [MOB-3726] convert all function expressions to function declaration

- ts/IterableInAppMessage.ts
- ts/IterableInboxMessageList.tsx
* [MOB-3750](https://iterable.atlassian.net/browse/MOB-3750)
* basically just moves `ViewToken` around and cleans up code slightly
> [MOB-3750] view token slight refactor

- package.json
- ts/IterableInbox.tsx
- yarn.lock
* [MOB-3383] (https://iterable.atlassian.net/browse/MOB-3383)
This pull request includes the functionality for inbox session tracking when the inbox tab is exited either through the navigator or internal linking. Session tracking when the app is minimized or closed will be addressed on another PR.
[MOB-3383]: https://iterable.atlassian.net/browse/MOB-3383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3383] inbox session tracking between tabs

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- android/src/main/java/com/iterable/reactnative/Serialization.java
- ios/RNIterableAPI/Serialization.swift
- ts/Iterable.ts
* [MOB-3923](https://iterable.atlassian.net/browse/MOB-3923)
* adds the allowed protocols list to the RN SDK's config, and connects it to the respective native platforms
> [MOB-3923] RN SDK allowed protocols

- SampleApp/javascript/yarn.lock
- SampleApp/typescript/yarn.lock
- android/src/main/java/com/iterable/reactnative/Serialization.java
- integration-testing/yarn.lock
- ios/RNIterableAPI/Serialization.swift
- ts/IterableConfig.ts
* N/A
* merges the RN SDK allowed protocols change already in `master`, into `inbox`
> merge master into inbox

- ios/RNIterableAPI/ReactIterableAPI.swift
- ts/IterableInbox.tsx
- ts/IterableInboxCustomizations.ts
- ts/IterableInboxDataModel.ts
- ts/IterableInboxMessageCell.tsx
- ts/IterableInboxMessageList.tsx
* [MOB-3826](https://iterable.atlassian.net/browse/MOB-3826)
This pull request includes the functionality to allow the initial message impression to be tracked and sent to the backend. The initial message impressions are calculated based on the message row height and the message list height. The initial message impressions are sent to the backend when the inbox session is started.
> [MOB-3826] address initial impression tracking

- ts/IterableInboxDataModel.ts
* [MOB-3932] (https://iterable.atlassian.net/browse/MOB-3932)
This pull request addresses the invalid date on the android side. I added a conversion of the createdAt value to a number when sent from the android SDK.
[MOB-3932]: https://iterable.atlassian.net/browse/MOB-3932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3932] addresses invalid date on Android implementation

- ts/IterableInboxCustomizations.ts
This pull request includes some minor changes to the IterableInboxCustomizations type object that correspond to the changes in the react native dev app.
> minor changes to the IterableInboxCustomizations type object

- Iterable-React-Native-SDK.podspec
- ios/RNIterableAPI/Serialization.swift
- ts/Iterable.ts
- ts/IterableAction.ts
- ts/IterableConfig.ts
- ts/IterableInAppManager.ts
- ts/IterableInAppMessage.ts
- ts/IterableInbox.tsx
- ts/IterableInboxDataModel.ts
- ts/IterableInboxMessageCell.tsx
- ts/IterableInboxMessageDisplay.tsx
- ts/IterableInboxMessageList.tsx
- ts/index.ts
* [MOB-4016] (https://iterable.atlassian.net/browse/MOB-4016)
This pull request addresses circular references with index.js. I did this by removing some of the circular imports to the index.js file.
[MOB-4016]: https://iterable.atlassian.net/browse/MOB-4016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4016] addresses circular references with index.js

- ts/IterableInbox.tsx
* [MOB-4044] (https://iterable.atlassian.net/browse/MOB-4044)
This pull request increases the duration of the sliding animation between the message list and message display.
[MOB-4044]: https://iterable.atlassian.net/browse/MOB-4044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4044] increase animation speed

- ts/IterableInbox.tsx
- ts/IterableInboxCustomizations.ts
* [MOB-4042] (https://iterable.atlassian.net/browse/MOB-4042)
This pull request sets the customization values across the customizations object as optional.
[MOB-4042]: https://iterable.atlassian.net/browse/MOB-4042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4042] sets customization values as optional

- ts/IterableInboxMessageDisplay.tsx
* [MOB-4038](https://iterable.atlassian.net/browse/MOB-4038)
This pull request updates the styling of the iterableInboxMessageDisplay component. This took significant restructuring of the view elements so that the message title is always centered.
> [MOB-4038] back button styling update

- ts/IterableInboxMessageDisplay.tsx
* [MOB-4038] (https://iterable.atlassian.net/browse/MOB-4038)
This pull request reorders some of the platform dependent styling.
[MOB-4038]: https://iterable.atlassian.net/browse/MOB-4038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4038] reorders some of the platform dependent styling

- ts/IterableInbox.tsx
* [MOB-4045] (https://iterable.atlassian.net/browse/MOB-4045)
This pull request adds the returnToInboxTrigger as a sent down prop value and calls returnToInbox when the trigger changes if the message is displayed.
[MOB-4045]: https://iterable.atlassian.net/browse/MOB-4045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4045] return to inbox functionality on tapping on inbox tab

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- package.json
- yarn.lock
* [MOB-4166](https://iterable.atlassian.net/browse/MOB-4166)
* releases 1.1.4 with new pointers to updated SDKs
> [MOB-4166] release 1.1.4

- android/build.gradle
- package.json
- yarn.lock
* [MOB-4169](https://iterable.atlassian.net/browse/MOB-4169)
* renames release to 1.2.0
> [MOB-4169] update version and add comment in build.gradle

- Iterable-React-Native-SDK.podspec
This fixes issue #307  
No JIRA ticket
Updates the deployment target to fix builds. Spec still needs to be pushed to cocoapods
> Update iOS Deployment Target

- .github/workflows/integration-test.yml
- Iterable-React-Native-SDK.podspec
- integration-testing/package.json
- integration-testing/yarn.lock
* N/A
* updates integration testing SDK to 1.2.1
> point integration testing to RN SDK 1.2.1

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
> point sample apps to newest SDK

- android/build.gradle
- package.json
- yarn.lock
* [MOB-4241](https://iterable.atlassian.net/browse/MOB-4241)
* releases a new RN SDK version with Android SDK 3.4.4
> [MOB-4241] version 1.2.2 and point to new android SDK

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-4245](https://iterable.atlassian.net/browse/MOB-4245)
* point internal stuff to RN SDK 1.2.2
> [MOB-4245] point integration tests and sample apps to RN SDK 1.2.2

- .github/workflows/integration-test.yml
- Iterable-React-Native-SDK.podspec
- SampleApp/javascript/package.json
- SampleApp/javascript/yarn.lock
- SampleApp/typescript/package.json
- SampleApp/typescript/yarn.lock
- android/build.gradle
- integration-testing/package.json
- integration-testing/yarn.lock
- package.json
- yarn.lock
* [MOB-4237](https://iterable.atlassian.net/browse/MOB-4237)
* updates `inbox` with the latest
> [MOB-4237] merge into inbox

- ts/IterableInboxMessageCell.tsx
* [MOB-4313](https://iterable.atlassian.net/browse/MOB-4313)
This fix will carryout the reset position of delete slider after the finger/pointer is lifted and panresponder gives movements towards right side.
> [MOB-4313] - Reset the delete slider

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- integration-testing/ios/example.xcodeproj/project.pbxproj
- integration-testing/ios/example/IterableAPISupport.swift
- integration-testing/ios/example/Pending.swift
- integration-testing/yarn.lock
- package.json
- yarn.lock
* [MOB-4299](https://iterable.atlassian.net/browse/MOB-4299)
* version 1.2.3
> [MOB-4299] version 1.2.3

- ts/IterableInboxCustomizations.ts
- ts/IterableInboxMessageCell.tsx
* [MOB-4368] (https://iterable.atlassian.net/browse/MOB-4368)
This pull request renames the message icon to message thumbnail to align with the Iterable UI.
[MOB-4368]: https://iterable.atlassian.net/browse/MOB-4368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4368] rename message icon

- package.json
- yarn.lock
* [MOB-4356] (https://iterable.atlassian.net/browse/MOB-4356)
Updates RN SDK to version 1.3.0.
[MOB-4356]: https://iterable.atlassian.net/browse/MOB-4356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4356] version 1.3.0 updates

- SampleApp/javascript/js/Config.sample.js
- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-4378] (https://iterable.atlassian.net/browse/MOB-4378)
This pull request updates the SDK version in the sample app and integration testing.
[MOB-4378]: https://iterable.atlassian.net/browse/MOB-4378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-4378] updates SDK version in sample app and integration testing

- package.json
- yarn.lock
* [MOB-4395](https://iterable.atlassian.net/browse/MOB-4395)
* release version 1.3.1
> [MOB-4395] version 1.3.1

- ts/Iterable.ts
- ts/IterableConfig.ts
- ts/IterableInAppManager.ts
- ts/IterableInboxDataModel.ts
- ts/IterableLogger.ts
- ts/__tests__/Iterable.spec.ts
- ts/__tests__/IterableInApp.spec.ts
* [MOB-2572](https://iterable.atlassian.net/browse/MOB-2572)
* creates `IterableLogger` specific to the RN SDK
* adds a boolean option in `IterableConfig` (default: `true`) to always print
* replaces anything in our SDK that previously used `console.log` to go through `IterableLogger`
> [MOB-2572] create a logger class and have option to disable logging

- Iterable-React-Native-SDK.podspec
- package.json
- yarn.lock
* [MOB-4493](https://iterable.atlassian.net/browse/MOB-4493)
* version 1.3.2 release
> [MOB-4493] update version and bindings

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- package.json
- yarn.lock
* [MOB-4583](https://iterable.atlassian.net/browse/MOB-4583)
version 1.3.3 release
> [MOB-4583] 1.3.3 release

- SampleApp/javascript/package.json
- SampleApp/javascript/yarn.lock
- SampleApp/typescript/package.json
- integration-testing/package.json
- integration-testing/ts/Login.tsx
* [MOB-4598](https://iterable.atlassian.net/browse/MOB-4598)
This pull request updates the SDK version in the sample app and integration testing.
> [MOB-4598] update sample apps and integration to 1.3.3

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- ts/Iterable.ts
- ts/__mocks__/MockRNIterableAPI.ts
- ts/__tests__/Iterable.spec.ts
* [MOB-4449](https://iterable.atlassian.net/browse/MOB-4449)
* adds RN bindings for `updateEmail` with token
> [MOB-4449] update email with token

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- package.json
- yarn.lock
* [MOB-4686](https://iterable.atlassian.net/browse/MOB-4686)
This pull request prepares the release of RN SDK version 1.3.4.
> [MOB-4686] prepares 1.3.4 release

- Iterable-React-Native-SDK.podspec
- android/build.gradle
- package.json
- yarn.lock
* [MOB-4691](https://iterable.atlassian.net/browse/MOB-4691)
This pull request includes the updates for the version 1.3.5 release.
> [MOB-4691] prepares version 1.3.5 release

- SampleApp/javascript/js/Config.sample.js
- SampleApp/javascript/package.json
- SampleApp/javascript/yarn.lock
- SampleApp/typescript/package.json
- integration-testing/package.json
- package.json
- yarn.lock
* [MOB-4699](https://iterable.atlassian.net/browse/MOB-4699)
This pull request includes updating the sample apps and integration testing to point to the newest release of the RN SDK.
> [MOB-4699] post 1.3.5 release

- package.json
- yarn.lock
* [MOB-4716](https://iterable.atlassian.net/browse/MOB-4716)
This pull request includes the updates for the release of RN SDK version 1.3.6.
> [MOB-4716] prepares 1.3.6 release

- ts/IterableInAppManager.ts
* [MOB-4949](https://iterable.atlassian.net/browse/MOB-4949)
This pull request adds descriptive comments to the IterableInAppManager.ts file to improve developer joy when using our React Native SDK.
> [MOB-4949] add descriptive comments to IterableInAppManager.ts

- ts/IterableConfig.ts
* [MOB-4984](https://iterable.atlassian.net/browse/MOB-4984)
This pull request includes updates to the IterableConfig.ts comments to align with support documentation.
> [MOB-4984] update IterableConfig.ts comments

- ts/IterableInAppManager.ts
* [MOB-5028](https://iterable.atlassian.net/browse/MOB-5028)
This pull request includes removing the promise processing from the SDK. The promise is returned by the SDK and processed on the application side.
> [MOB-5028] removes promise processing

- CHANGELOG.md
- Iterable-React-Native-SDK.podspec
- android/build.gradle
- package.json
- yarn.lock
* [MOB-4207](https://iterable.atlassian.net/browse/MOB-4207)
* version 1.3.7
> [MOB-4207] version 1.3.7

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-5093](https://iterable.atlassian.net/browse/MOB-5093)
* update tests and apps
> [MOB-5093] point to RN SDK 1.3.7

- android/src/main/java/com/iterable/reactnative/Serialization.java
- ios/RNIterableAPI/Serialization.swift
- ts/IterableConfig.ts
* [MOB-5116](https://iterable.atlassian.net/browse/MOB-5116)
> [MOB-5116] add iOS in memory option

- CHANGELOG.md
- package.json
- yarn.lock
* [MOB-5135](https://iterable.atlassian.net/browse/MOB-5135)
> [MOB-5135] version 1.3.8

- Iterable-React-Native-SDK.podspec
> point to iOS SDK 6.4.9

- CHANGELOG.md
- package.json
* [MOB-5137](https://iterable.atlassian.net/browse/MOB-5137)
> [MOB-5137] version 1.3.9

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-5136](https://iterable.atlassian.net/browse/MOB-5136)
> [MOB-5136] update apps tests

- README.md
* [MOB-5172](https://iterable.atlassian.net/browse/MOB-5172)
This pull request updates the verison mapping table up to version 1.3.9.
> [MOB-5172] updates version mapping table up to RN SDK version 1.3.9

- ts/__tests__/Iterable.spec.ts
* [MOB-5187](https://iterable.atlassian.net/browse/MOB-5187)
This pull request adds unit tests for get/setEmail and get/setUserId with token. Associated slab doc outlining how to set up test methods [here](https://iterable.slab.com/posts/how-to-write-test-methods-for-the-rn-sdk-g2pa6fihl).
> [MOB-5187] sets up unit tests for get/setEmail and get/setUserId with token

- ts/__mocks__/MockRNIterableAPI.ts
- ts/__tests__/IterableInApp.spec.ts
* [MOB-5252](https://iterable.atlassian.net/browse/MOB-5252)
This pull request sets up clickedUrl and setter for MockRNIterableAPI class, and refactors the showMessage unit test.
> [MOB-5252] refactors showMessage unit test

- SampleApp/javascript/js/App.js
- SampleApp/javascript/js/Config.sample.js
- SampleApp/javascript/yarn.lock
* [MOB-4810](https://iterable.atlassian.net/browse/MOB-4810)
This pull request includes detailed comments on the set up of the React Native SDK in the provided sample app.
> [MOB-4810] adds detailed comments for the sample apps

- ts/IterableInboxMessageDisplay.tsx
This pull request fixes the imports for the message display component.
> updates imports for message display component

- babel.config.js
- jest.config.js
- ts/__mocks__/MockLinking.ts
- ts/__mocks__/MockRNIterableAPI.ts
- ts/__mocks__/jest.setup.ts
- ts/__tests__/Iterable.spec.ts
- ts/__tests__/IterableInApp.spec.ts
- ts/__tests__/TestHelper.ts
- tsconfig.json
* [MOB-5314](https://iterable.atlassian.net/browse/MOB-5314)
This pull request applies linting changes to the test files and config files.
> [MOB-5314] linting changes to test files and config files

- Iterable-React-Native-SDK.podspec
- package.json
- yarn.lock
* [MOB-5367](https://iterable.atlassian.net/browse/MOB-5367)
This pull request includes the changes for the RN version 1.3.10 release.
[MOB-5367]: https://iterable.atlassian.net/browse/MOB-5367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5367] prepares 1.3.10 release

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-5372](https://iterable.atlassian.net/browse/MOB-5372)
This pull request updates the version in the sample apps and integration tests post version 1.3.10 release.
[MOB-5372]: https://iterable.atlassian.net/browse/MOB-5372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5372] updates version for sample apps and integration tests

- README.md
* [MOB-5368](https://iterable.atlassian.net/browse/MOB-5368)
This pull request updates the version mapping table.
[MOB-5368]: https://iterable.atlassian.net/browse/MOB-5368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5368] updates version mapping table

- SampleApp/javascript/js/DetailScreen.js
* [MOB-5333](https://iterable.atlassian.net/browse/MOB-5333)
Addresses outstanding comments for MOB-5333.
[MOB-5333]: https://iterable.atlassian.net/browse/MOB-5333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5333] addresses comments

- SampleApp/javascript/js/DetailScreen.js
Reverts Iterable/react-native-sdk#471
> Revert "[MOB-5333] addresses comments"

- android/src/main/java/com/iterable/iterableapi/RNIterableInternal.java
- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- android/src/main/java/com/iterable/reactnative/Serialization.java
- ios/RNIterableAPI/ReactIterableAPI.swift
- ios/RNIterableAPI/Serialization.swift
- ts/IterableInAppMessage.ts
- ts/__tests__/IterableInApp.spec.ts
* [MOB-5621](https://iterable.atlassian.net/browse/MOB-5621)
- uses the proper data type for custom payloads on RN to work on both platforms
[MOB-5621]: https://iterable.atlassian.net/browse/MOB-5621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5621] align RN side data type for in-app customPayload field

- Iterable-React-Native-SDK.podspec
- README.md
- package.json
- yarn.lock
* [MOB-5734](https://iterable.atlassian.net/browse/MOB-5734)
[MOB-5734]: https://iterable.atlassian.net/browse/MOB-5734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5734] version 1.3.11

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-5747](https://iterable.atlassian.net/browse/MOB-5747)
[MOB-5747]: https://iterable.atlassian.net/browse/MOB-5747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5747] update pointers

- android/src/main/java/com/iterable/iterableapi/RNIterableInternal.java
- ts/IterableInAppMessage.ts
* [MOB-5766](https://iterable.atlassian.net/browse/MOB-5766)
* put back android binding
* put back RN custom payload data type
[MOB-5766]: https://iterable.atlassian.net/browse/MOB-5766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5766] readjust data type and android binding

- Iterable-React-Native-SDK.podspec
- README.md
- SampleApp/javascript/yarn.lock
- SampleApp/typescript/yarn.lock
- integration-testing/yarn.lock
- package.json
- yarn.lock
* [MOB-5772](https://iterable.atlassian.net/browse/MOB-5772)
[MOB-5772]: https://iterable.atlassian.net/browse/MOB-5772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5772] version 1.3.12

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-5966](https://iterable.atlassian.net/browse/MOB-5966)
[MOB-5966]: https://iterable.atlassian.net/browse/MOB-5966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5966] update sample/integration to 1.3.12

- SampleApp/javascript/yarn.lock
- SampleApp/typescript/yarn.lock
- integration-testing/yarn.lock
> updating dependencies

- SampleApp/javascript/js/DetailScreen.js
- SampleApp/javascript/yarn.lock
- ts/index.ts
* [MOB-5840](https://iterable.atlassian.net/browse/MOB-5840)
This pull request includes a fix to allow proper import of IterableCommerceItem.
[MOB-5840]: https://iterable.atlassian.net/browse/MOB-5840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5840] commerce item import bug

- android/build.gradle
- android/src/main/java/com/iterable/reactnative/Serialization.java
- ts/IterableConfig.ts
- ts/__tests__/Iterable.spec.ts
- yarn.lock
* [MOB-5898](https://iterable.atlassian.net/browse/MOB-5898)
> Pointing to latest Android version with encryption flag enabled
[MOB-5898]: https://iterable.atlassian.net/browse/MOB-5898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5898] - Encryption Flag with 3.4.11

- README.md
- package.json
- yarn.lock
* [MOB-6036](https://iterable.atlassian.net/browse/MOB-6036)
> Prepare for 1.3.13 release.
Android version already updated in previous PR for Encryption changes. iOS pointing to same version as before.
[MOB-6036]: https://iterable.atlassian.net/browse/MOB-6036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6036] - Preparing for 1.3.13

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- android/src/main/java/com/iterable/reactnative/Serialization.java
- ios/RNIterableAPI/Serialization.swift
- ts/IterableConfig.ts
- ts/IterableDataRegion.ts
- ts/__tests__/Iterable.spec.ts
- yarn.lock
* [MOB-5870](https://iterable.atlassian.net/browse/MOB-5870)
- creates the IterableDataRegion enum which will inform the native layer
- adds the dataRegion value to the IterableConfig class
- updates the unit tests for the default config values for the added dataRegion value
[MOB-5870]: https://iterable.atlassian.net/browse/MOB-5870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5870] add data center configuration

- ios/RNIterableAPI/Serialization.swift
- yarn.lock
* [MOB-6317](https://iterable.atlassian.net/browse/MOB-6317)
> This pull request maps the integer data region value in the RN SDK config to the corresponding IterableDataRegion enum value in the native iOS layer.
[MOB-6317]: https://iterable.atlassian.net/browse/MOB-6317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6317] data region deserialization fix for iOS layer

- ts/index.ts
* [MOB-6316](https://iterable.atlassian.net/browse/MOB-6316)
This pull request adds IterableDataRegion to index.ts for better organization.
[MOB-6316]: https://iterable.atlassian.net/browse/MOB-6316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6316] add iterable data region to index.ts

- CHANGELOG.md
- Iterable-React-Native-SDK.podspec
- README.md
- android/build.gradle
- package.json
- yarn.lock
* [MOB-6474](https://iterable.atlassian.net/browse/MOB-6474)
> This pull request updates the version mappings and yarn.lock for release of version 1.3.14.
[MOB-6474]: https://iterable.atlassian.net/browse/MOB-6474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6474] prepares for 1.3.14 release

- CHANGELOG.md
- README.md
- android/build.gradle
- integration-testing/ios/example/ReactE2E.swift
- package.json
- yarn.lock
* [MOB-6508](https://iterable.atlassian.net/browse/MOB-6508)
>Prepare for 1.3.15
[MOB-6508]: https://iterable.atlassian.net/browse/MOB-6508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prepare for 1.3.15

- SampleApp/javascript/js/SettingsTab.js
- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- integration-testing/ts/Login.tsx
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- ts/Iterable.ts
- ts/__tests__/Iterable.spec.ts
* [MOB-6055](https://iterable.atlassian.net/browse/MOB-6055)
> Add callbacks for setEmail/setUserId, and it returns success/failure based on device token is registered successfully or not. It will always return success if autoPushRegistration is false.
[MOB-6055]: https://iterable.atlassian.net/browse/MOB-6055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6055] callback on setEmail/setUserId

- CHANGELOG.md
- Iterable-React-Native-SDK.podspec
- README.md
- android/build.gradle
- package.json
- yarn.lock
* [MOB-6601](https://iterable.atlassian.net/browse/MOB-6601)
> This pull request prepares for 1.3.16 release.
[MOB-6601]: https://iterable.atlassian.net/browse/MOB-6601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6601] prepares for 1.3.16 release

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- ios/RNIterableAPI/RNIterableAPI.m
- ios/RNIterableAPI/ReactIterableAPI.swift
- ts/IterableInAppManager.ts
- ts/__tests__/IterableInApp.spec.ts
- ts/types.ts
* [MOB-5730](https://iterable.atlassian.net/browse/MOB-5730)
> Add callbacks to reading/removing in-app messages.
[MOB-5730]: https://iterable.atlassian.net/browse/MOB-5730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB 5730] Add callbacks to reading/removing in-app messages

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-6869](https://iterable.atlassian.net/browse/MOB-6869)
> This pull request updates the pointers for the sample apps and integration testing.
[MOB-6869]: https://iterable.atlassian.net/browse/MOB-6869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6869] post 1.3.16 release

- CHANGELOG.md
- README.md
- android/build.gradle
- package.json
- yarn.lock
* [MOB-7049](https://iterable.atlassian.net/browse/MOB-7049)
> Prepare for 1.3.17
[MOB-7049]: https://iterable.atlassian.net/browse/MOB-7049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB - 7049] - Prepare for 1.3.17

- SampleApp/javascript/js/App.js
- SampleApp/javascript/js/HomeScreen.js
- SampleApp/javascript/js/NotificationViewScreen.d.ts
- SampleApp/javascript/js/NotificationViewScreen.js
- SampleApp/javascript/js/components/IterableNotificationView.tsx
- SampleApp/javascript/js/types/commonType.ts
- ts/components/IterableNotificationView.tsx
- ts/index.ts
- ts/types/commonType.ts
> Added Notification View

- ts/IterableConfig.ts
Added enableAnonTracking flag to support anonymous tracking on/off.
> MOB-8476: Added enableAnonTracking flag

- CHANGELOG.md
- Iterable-React-Native-SDK.podspec
- README.md
- android/build.gradle
- package.json
- yarn.lock
* [MOB-8359](https://iterable.atlassian.net/browse/MOB-8359)
> This pull request prepares for version 1.3.18 release.
[MOB-8359]: https://iterable.atlassian.net/browse/MOB-8359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> updates versions and yarn.lock

- Iterable-React-Native-SDK.podspec
> Bump min iOS version

- package.json
> react-native dev-dependecy upgrade to fix vulnerability issues

- CHANGELOG.md
- README.md
- package.json
- yarn.lock
* [MOB-8847](https://iterable.atlassian.net/browse/MOB-8847)
> This pull request prepares version 1.3.19 for release.
[MOB-8847]: https://iterable.atlassian.net/browse/MOB-8847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8847] prepare for version 1.3.19 release

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
* [MOB-8863](https://iterable.atlassian.net/browse/MOB-8863)
> This pull request updates the pointers for sample apps and integration testing to the latest.
[MOB-8863]: https://iterable.atlassian.net/browse/MOB-8863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8863] post 1.3.19 release checklist

- Iterable-React-Native-SDK.podspec
- README.md
- SampleApp/javascript/ios/Podfile
- SampleApp/typescript/ios/Podfile
- integration-testing/ios/Podfile
- integration-testing/ios/example.xcodeproj/project.pbxproj
- integration-testing/ios/scripts/run_test.sh
- yarn.lock
* [MOB-9372](https://iterable.atlassian.net/browse/MOB-9372)
> Prepares for 1.3.20
> Points to definite swift SDK version avoiding version bumping
[MOB-9372]: https://iterable.atlassian.net/browse/MOB-9372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9372] - Prepare for 1.3.20

- CHANGELOG.md
- package.json
* [MOB-9372](https://iterable.atlassian.net/browse/MOB-9372)
> Prepare for 1.3.20
[MOB-9372]: https://iterable.atlassian.net/browse/MOB-9372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prepare for 1.3.20-part 2

- yarn.lock
* [MOB-9372](https://iterable.atlassian.net/browse/MOB-9372)
[MOB-9372]: https://iterable.atlassian.net/browse/MOB-9372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prepare for 1.3.20-iii

- SampleApp/javascript/package.json
- SampleApp/typescript/package.json
- integration-testing/package.json
> Post release commit to point sample app and integration test to released SDK
> Post release 1.3.20

- ios/RNIterableAPI/Serialization.swift
- ts/IterableConfig.ts
- ts/IterablePushPlatform.ts
- yarn.lock
* [MOB-9381](https://iterable.atlassian.net/browse/MOB-9381)
Add pushPlatform config for iOS.
To use, developers will have to set the config variable as follows: config.pushPlatform = IterablePushPlatform.production
or it can be .sandbox or .auto as well.
This will allow to manually set the platform type if automatic is not working.
[MOB-9381]: https://iterable.atlassian.net/browse/MOB-9381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9381] - Push platform Configuration for iOS

- CHANGELOG.md
- yarn.lock
* [MOB-10409](https://iterable.atlassian.net/browse/MOB-10409)
>  Prepare for 1.3.21
[MOB-10409]: https://iterable.atlassian.net/browse/MOB-10409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10409] - Prepare for 1.3.21

- lefthook.yml
* [MOB-9680](https://iterable.atlassian.net/browse/MOB-9680)
Fixed lefthook
[MOB-9680]: https://iterable.atlassian.net/browse/MOB-9680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9680] Fix lefthook

- android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
- example/src/hooks/useIterableApp.tsx
- src/core/classes/Iterable.ts
- src/core/hooks/useDeviceOrientation.tsx
- src/inApp/classes/IterableInAppMessage.ts
- src/inbox/classes/IterableInboxDataModel.ts
- src/inbox/components/IterableInbox.tsx
- src/inbox/components/IterableInboxMessageCell.tsx
- src/inbox/components/IterableInboxMessageList.tsx
* [MOB-10289](https://iterable.atlassian.net/browse/MOB-10289)
Created tickets for todos and added them to a tech debt epic
[MOB-10289]: https://iterable.atlassian.net/browse/MOB-10289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10289] Make todos into tickets

- example/README.md
- src/itblBuildInfo.ts
* [MOB-10606](https://iterable.atlassian.net/browse/MOB-10606)
- Updated readme as per the ticket
- Updated incorrect build version
[MOB-10606]: https://iterable.atlassian.net/browse/MOB-10606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10606] example-app-readme-suggestions-corrections

- README.md
* [DOCS-4993](https://iterable.atlassian.net/browse/DOCS-4993)
Removed link to beta disclaimer.
[DOCS-4993]: https://iterable.atlassian.net/browse/DOCS-4993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-4993] Removed beta disclaimer link

- .github/workflows/release-prerelease.yml
- .github/workflows/release-stable.yml
* [MOB-11998](https://iterable.atlassian.net/browse/MOB-11998)
Publish to npm when publishing in github
Create @next tag release when merging into master
Create @alpha tag release when merging into alpha
Create @beta tag release when merging into beta
Create @rc tag release when merging into rc 
[MOB-11998]: https://iterable.atlassian.net/browse/MOB-11998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-11998] rn-create-next-release-and-publish-scripts
